// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zetnlzvtouzavfhiwesn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpldG5senZ0b3V6YXZmaGl3ZXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDEzMDMsImV4cCI6MjA3MzUxNzMwM30.5Am1p7gurgaUtNZztum5Oj_4f9IFWXl47_K1IqLkiV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});